package vn.com.gsoft.categories.model.dto;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.*;
import vn.com.gsoft.categories.model.system.BaseRequest;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class ThuocsReq extends BaseRequest {

    private Integer thuocId;
    private String maThuoc;
    private String tenThuoc;
    private String thongTin;
    private Integer heSo;
    private BigDecimal giaNhap;
    private BigDecimal giaBanBuon;
    private BigDecimal giaBanLe;
    private BigDecimal soDuDauKy;
    private BigDecimal giaDauKy;
    private Integer gioiHan;
    private String nhaThuocMaNhaThuoc;
    private Integer nhomThuocMaNhomThuoc;
    private Integer nuocMaNuoc;
    private Integer dangBaoCheMaDangBaoChe;
    private Integer donViXuatLeMaDonViTinh;
    private Integer donViThuNguyenMaDonViTinh;
    private Date created;
    private Date modified;
    private Integer createdByUserId;
    private Integer modifiedByUserId;
    private String barCode;
    private Boolean hoatDong;
    private Boolean hangTuVan;
    private Date hanDung;
    private Integer duTru;
    private Boolean active;
    private String nhaThuocMaNhaThuocCreate;
    private Integer recordStatusID;
    private Integer connectivityDrugID;
    private BigDecimal connectivityDrugFactor;
    private Integer maNhaCungCap;
    private Integer parentDrugId;
    private Integer metadataHash;
    private Integer rpMetadataHash;
    private Integer referenceId;
    private BigDecimal discount;
    private Boolean discountByRevenue;
    private Integer saleTypeId;
    private BigDecimal saleOff;
    private String saleDescription;
    private Date saleStartDate;
    private Date saleEndDate;
    private Boolean scorable;
    private String imageThumbUrl;
    private String imagePreviewUrl;
    private Integer connectivityTypeId;
    private Integer archivedId;
    private Integer storeId;
    private Integer productTypeId;
    private String serialNumber;
    private BigDecimal moneyToOneScoreRate;
    @Column(name = "Presentation")
    private Boolean presentation;
    @Column(name = "NameHash")
    private Long nameHash;
    @Column(name = "RegisteredNo")
    private String registeredNo;
    @Column(name = "ActiveSubstance")
    private String activeSubstance;
    @Column(name = "Contents")
    private String contents;
    @Column(name = "PackingWay")
    private String packingWay;
    @Column(name = "Manufacturer")
    private String manufacturer;
    @Column(name = "CountryOfManufacturer")
    private String countryOfManufacturer;
    @Column(name = "CountryId")
    private Integer countryId;
    @Column(name = "ConnectivityId")
    private String connectivityId;
    @Column(name = "ConnectivityResult")
    private String connectivityResult;
    @Column(name = "ConnectivityDateTime")
    private Date connectivityDateTime;
    @Column(name = "DosageForms")
    private String dosageForms;
    @Column(name = "SmallestPackingUnit")
    private String smallestPackingUnit;
    @Column(name = "Importers")
    private String importers;
    @Column(name = "DeclaredPrice")
    private BigDecimal declaredPrice;
    @Column(name = "ConnectivityCode")
    private String connectivityCode;
    @Column(name = "CodeHash")
    private Long codeHash;
    @Column(name = "ConnectivityStatusId")
    private Integer connectivityStatusId;
    @Column(name = "OrganizeDeclaration")
    private String organizeDeclaration;
    @Column(name = "CountryRegistration")
    private String countryRegistration;
    @Column(name = "AddressRegistration")
    private String addressRegistration;
    @Column(name = "AddressManufacture")
    private String addressManufacture;
    @Column(name = "Identifier")
    private String identifier;
    @Column(name = "Classification")
    private String classification;
    @Column(name = "ForWholesale")
    private Integer forWholesale;
    @Column(name = "HoatChat")
    private String hoatChat;
    @Column(name = "TypeService")
    private Integer typeService;
    @Column(name = "TypeServices")
    private Integer typeServices;
    @Column(name = "IdTypeService")
    private Integer idTypeService;
    @Column(name = "IdClinic")
    private Integer idClinic;
    @Column(name = "CountNumbers")
    private Integer countNumbers;
    @Column(name = "IdWarehouseLocation")
    private Integer idWarehouseLocation;
    @Column(name = "HamLuong")
    private String hamLuong;
    @Column(name = "QuyCachDongGoi")
    private String quyCachDongGoi;
    @Column(name = "NhaSanXuat")
    private String nhaSanXuat;
    @Column(name = "Advantages")
    private String advantages;
    @Column(name = "UserObject")
    private String userObject;
    @Column(name = "UserManual")
    private String userManual;
    @Column(name = "Pharmacokinetics")
    private String pharmacokinetics;
    @Column(name = "IsShow_CustomerWebsite")
    private Boolean isShowCustomerWebsite;
    @Column(name = "Flag")
    private Boolean flag;
    @Column(name = "GroupIdMapping")
    private Integer groupIdMapping;
    @Column(name = "GroupNameMapping")
    private String groupNameMapping;
    @Column(name = "ResultService")
    private String resultService;
    @Column(name = "TitleResultService")
    private String titleResultService;
    @Column(name = "TypeResultService")
    private Integer typeResultService;
    @Column(name = "GroupIdMappingV2")
    private Integer groupIdMappingV2;
    @Column(name = "StorageConditions")
    private String storageConditions;
    @Column(name = "StorageLocation")
    private String storageLocation;
    @Column(name = "MappingDate")
    private Date mappingDate;
    @Column(name = "ChiDinh")
    private String chiDinh;
    @Column(name = "ChongChiDinh")
    private String chongChiDinh;
    @Column(name = "XuatXu")
    private String xuatXu;
    @Column(name = "LuuY")
    private String luuY;
    @Column(name = "PromotionalDiscounts")
    private BigDecimal promotionalDiscounts;
    @Column(name = "EnablePromotionalDiscounts")
    private Boolean enablePromotionalDiscounts;
    @Column(name = "DescriptionOnWebsite")
    private String descriptionOnWebsite;
    @Column(name = "ImgReferenceDrugId")
    private Integer imgReferenceDrugId;
    @Column(name = "UserUploadImgDate")
    private Date userUploadImgDate;
    @Column(name = "UserUploadImgId")
    private Integer userUploadImgId;
    @Column(name = "StatusConfirm")
    private Integer statusConfirm;
    @Column(name = "UserIdConfirm")
    private Integer userIdConfirm;
    @Column(name = "UserIdMapping")
    private Integer userIdMapping;
}

